import type { Category, Product } from './types'

// Número de WhatsApp para recibir cotizaciones (formato internacional sin '+').
export const WHATSAPP_NUMBER = '573011234567'

export const CATEGORIES: Category[] = [
  { id: 'brochas-rodillos', name: 'Brochas y Rodillos', slug: 'brochas-rodillos' },
  { id: 'herramientas', name: 'Herramientas Manuales', slug: 'herramientas' },
  { id: 'electricas', name: 'Herramientas Eléctricas', slug: 'electricas' },
  { id: 'adhesivos', name: 'Adhesivos y Cintas', slug: 'adhesivos' },
  { id: 'seguridad', name: 'Seguridad Industrial', slug: 'seguridad' },
]

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Brocha Profesional 3"',
    brand: 'Kovex Pro',
    sku: 'BR-300',
    categoryId: 'brochas-rodillos',
    price: 4900,
    unit: 'Unidad',
    image: '/kovex/brocha-profesional.png',
    description:
      'Brocha profesional de 3 pulgadas con cerda natural y mango ergonómico de madera. Ideal para acabados finos en pintura y barniz.',
    stock: 480,
    featured: true,
  },
  {
    id: 'p2',
    name: 'Set de Brochas x5 Piezas',
    brand: 'Kovex Pro',
    sku: 'BR-SET5',
    categoryId: 'brochas-rodillos',
    price: 18900,
    unit: 'Set x5',
    image: '/kovex/set-brochas.png',
    description:
      'Juego de 5 brochas de distintos tamaños (1" a 4") con mango plástico resistente. Cobertura completa para todo tipo de trabajo.',
    stock: 220,
    featured: true,
  },
  {
    id: 'p3',
    name: 'Rodillo Antigota 9" + Repuesto',
    brand: 'Kovex Pro',
    sku: 'RD-900',
    categoryId: 'brochas-rodillos',
    price: 12500,
    unit: 'Unidad',
    image: '/kovex/rodillo.png',
    description:
      'Rodillo de 9 pulgadas con felpa antigota de alta absorción, incluye mango metálico y repuesto adicional.',
    stock: 310,
    featured: true,
  },
  {
    id: 'p4',
    name: 'Taladro Percutor Inalámbrico 20V',
    brand: 'Kovex Power',
    sku: 'TP-20V',
    categoryId: 'electricas',
    price: 189000,
    unit: 'Unidad',
    image: '/kovex/taladro.png',
    description:
      'Taladro percutor inalámbrico de 20V con batería de litio, portabrocas de 13mm y 2 velocidades. Incluye maletín y cargador.',
    stock: 65,
    featured: true,
  },
  {
    id: 'p5',
    name: 'Espátula de Acero 4"',
    brand: 'Kovex Tools',
    sku: 'ES-400',
    categoryId: 'herramientas',
    price: 3200,
    unit: 'Unidad',
    image: '/kovex/espatula.png',
    description:
      'Espátula de acero inoxidable de 4 pulgadas con mango plástico antideslizante. Perfecta para masilla y estuco.',
    stock: 540,
    featured: false,
  },
  {
    id: 'p6',
    name: 'Cinta de Enmascarar 1" x 40m',
    brand: 'Kovex Tape',
    sku: 'CE-140',
    categoryId: 'adhesivos',
    price: 2800,
    unit: 'Rollo',
    image: '/kovex/cinta-enmascarar.png',
    description:
      'Cinta de enmascarar de papel crepé de 1 pulgada x 40 metros. Adhesión limpia y remoción sin residuos.',
    stock: 900,
    featured: true,
  },
  {
    id: 'p7',
    name: 'Guantes de Seguridad Industrial',
    brand: 'Kovex Safe',
    sku: 'GT-IND',
    categoryId: 'seguridad',
    price: 5600,
    unit: 'Par',
    image: '/kovex/guantes.png',
    description:
      'Guantes de trabajo con recubrimiento de nitrilo, alta resistencia a la abrasión y excelente agarre en seco y húmedo.',
    stock: 420,
    featured: false,
  },
  {
    id: 'p8',
    name: 'Cepillo de Acero con Mango',
    brand: 'Kovex Tools',
    sku: 'CA-100',
    categoryId: 'herramientas',
    price: 4100,
    unit: 'Unidad',
    image: '/kovex/cepillo-acero.png',
    description:
      'Cepillo de cerdas de acero con mango de madera. Ideal para remover óxido, pintura vieja y limpieza de superficies.',
    stock: 380,
    featured: false,
  },
  {
    id: 'p9',
    name: 'Brocha Angular 2"',
    brand: 'Kovex Pro',
    sku: 'BR-200A',
    categoryId: 'brochas-rodillos',
    price: 3800,
    unit: 'Unidad',
    image: '/kovex/brocha-profesional.png',
    description:
      'Brocha angular de 2 pulgadas para trabajo de precisión en esquinas, marcos y molduras.',
    stock: 260,
    featured: false,
  },
  {
    id: 'p10',
    name: 'Cinta Doble Faz 24mm x 10m',
    brand: 'Kovex Tape',
    sku: 'CD-2410',
    categoryId: 'adhesivos',
    price: 7400,
    unit: 'Rollo',
    image: '/kovex/cinta-enmascarar.png',
    description:
      'Cinta doble faz de espuma de alta adherencia, 24mm x 10m. Fijación permanente para interiores y exteriores.',
    stock: 340,
    featured: false,
  },
  {
    id: 'p11',
    name: 'Rodillo de Espuma 4" x2',
    brand: 'Kovex Pro',
    sku: 'RD-400E',
    categoryId: 'brochas-rodillos',
    price: 6900,
    unit: 'Pack x2',
    image: '/kovex/rodillo.png',
    description:
      'Pack de 2 mini rodillos de espuma de 4 pulgadas para acabados lisos en esmaltes y lacas.',
    stock: 410,
    featured: false,
  },
  {
    id: 'p12',
    name: 'Gafas de Protección Antiempañante',
    brand: 'Kovex Safe',
    sku: 'GF-ANT',
    categoryId: 'seguridad',
    price: 8900,
    unit: 'Unidad',
    image: '/kovex/guantes.png',
    description:
      'Gafas de seguridad con lente policarbonato antiempañante y protección UV. Cumplen norma de seguridad industrial.',
    stock: 190,
    featured: false,
  },
]
