/**
 * Copia el catálogo de la base local a la base de producción.
 *
 *   pnpm db:copy "postgresql://…"   (la cadena del pooler de Supabase)
 *
 * Copia configuración, proveedores, categorías, productos, imágenes subidas y
 * usuarios del panel. NO copia clientes ni pedidos: son datos de prueba.
 *
 * Es idempotente: vuelve a correrlo y deja la base destino igual que la local.
 * Antes de copiar exige que el destino tenga las tablas creadas (corre primero
 * `DATABASE_URL="…" pnpm db:migrate`).
 */
import postgres from 'postgres'
import { db } from '@/lib/server/db'

const destinoUrl = process.argv[2]
if (!destinoUrl?.startsWith('postgres')) {
  console.error('Uso: pnpm db:copy "postgresql://usuario:clave@host:6543/postgres"')
  process.exit(1)
}

/** Orden de copia: respeta las llaves foráneas. */
const TABLAS = [
  { nombre: 'suppliers', identidad: true },
  { nombre: 'categories', identidad: true },
  { nombre: 'products', identidad: true },
  { nombre: 'uploads', identidad: false },
  { nombre: 'admin_users', identidad: true },
] as const

const LOTE = 200

async function main() {
  const origen = db()
  const destino = postgres(destinoUrl, {
    prepare: false,
    idle_timeout: 20,
    connect_timeout: 20,
    onnotice: () => {},
    // Mismo traductor de nombres que usa la aplicación: las filas vienen en
    // camelCase y las columnas de la base son snake_case.
    transform: { column: { from: postgres.toCamel, to: postgres.fromCamel }, undefined: null },
  })

  // 1. El destino tiene que estar migrado.
  const [{ existe }] = await destino<{ existe: boolean }[]>`
    select exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'products') as existe
  `
  if (!existe) {
    console.error('La base de destino no tiene las tablas. Corre primero las migraciones:')
    console.error(`   DATABASE_URL="${destinoUrl.replace(/:[^:@]*@/, ':***@')}" pnpm db:migrate`)
    await Promise.all([origen.end(), destino.end()])
    process.exit(1)
  }

  // 2. Configuración de la tienda (fila única).
  const [settings] = await origen`select * from public.store_settings where id`
  const { id: _id, updatedAt: _u, ...valores } = settings as Record<string, unknown>
  await destino`update public.store_settings set ${destino(valores as never, Object.keys(valores))} where id`
  console.log('configuración de la tienda copiada')

  // 3. Tablas de catálogo.
  for (const { nombre, identidad } of TABLAS) {
    const filas = await origen`select * from public.${origen(nombre)} order by id`
    if (filas.length === 0) {
      console.log(`${nombre}: sin filas`)
      continue
    }
    await destino`delete from public.${destino(nombre)}`
    const columnas = Object.keys(filas[0])
    // Las columnas id son "generated always": se permiten valores propios mientras
    // dure la copia y después vuelven a su definición original.
    if (identidad) await destino.unsafe(`alter table public.${nombre} alter column id set generated by default`)
    for (let i = 0; i < filas.length; i += LOTE) {
      const lote = filas.slice(i, i + LOTE)
      await destino`insert into public.${destino(nombre)} ${destino(lote as never, columnas)}`
    }
    if (identidad) {
      await destino.unsafe(`alter table public.${nombre} alter column id set generated always`)
      await destino.unsafe(
        `select setval(pg_get_serial_sequence('public.${nombre}', 'id'), coalesce((select max(id) from public.${nombre}), 1))`,
      )
    }
    console.log(`${nombre}: ${filas.length} filas`)
  }

  // 4. Comprobación final.
  const [{ productos }] = await destino<{ productos: number }[]>`
    select count(*)::int as productos from public.products where is_active
  `
  const [{ categorias }] = await destino<{ categorias: number }[]>`select count(*)::int as categorias from public.categories`
  const [{ admins }] = await destino<{ admins: number }[]>`select count(*)::int as admins from public.admin_users`
  console.log(`\nEn producción: ${productos} productos visibles · ${categorias} categorías · ${admins} usuario(s) del panel`)

  await Promise.all([origen.end(), destino.end()])
}

main().catch(async (error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
